all:
	cd libft && make $@
	cd printf && make $@
	cd gnl && make $@

bonus: 
	cd libft && make $@
	cd printf && make $@
	cd gnl && make $@

clean:
	cd libft && make $@
	cd printf && make $@
	cd gnl && make $@

fclean:
	cd libft && make $@
	cd printf && make $@
	cd gnl && make $@

re:
	cd libft && make $@
	cd printf && make $@
	cd gnl && make $@

re_bonus:
	cd libft && make $@
	cd printf && make $@
	cd gnl && make $@

.PHONY: all bonus clean fclean re re_bonus
